### ISSUE TITLE
Paid amount not detected

### ISSUE THREAD

**Issue by inthaiguy** [cardano-mercury/cardano-mercury-woocommerce#7]
Real world test results based on 2 payments and 3 orders with failed status:
- Received 1 payment of the exact ADA amount requested by plug-in, and payment was not detected as paid. Payment was exact to 8 decimal places.  x.xxxxxxxx 
- Received 1 payment not matching the other 2 possible orders.  Required to guess which users, based on timestamp of the order and ADA payment.

**Comment by Crypto2099** [comment]
This issue should be address with the soon to be released version 2.0 of the plugin which has been specifically focused on ensuring that amounts for each order are unique and detection is more reliable (thanks to the new Action Scheduler bundled into the plugin and WooCommerce).

**Comment by Crypto2099** [comment]
This should be resolved as of v2.0-RC2.

Moved to recording all transactions in the merchant wallet to a WordPress custom post type which allows for better and more accurate monitoring of wallet activity to be matched with order payment. Also introduce a tiny, custom table to keep track of unique dust amounts ensuring that each transaction always has a custom amount of ADA due to differentiate.
